[package]
name = "leaky"
version = "0.1.0"
description = "A program that deliberately leaks memory by means of a reference cycle"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
